python3 build_medicalgraph.py
Traceback (most recent call last):
  File "build_medicalgraph.py", line 269, in <module>
    handler = MedicalGraph()
  File "build_medicalgraph.py", line 19, in __init__
    password="123456")
  File "/usr/local/lib/python3.6/site-packages/py2neo/database.py", line 288, in __init__
    self.service = GraphService(profile, **settings)
  File "/usr/local/lib/python3.6/site-packages/py2neo/database.py", line 115, in __init__
    profile = ServiceProfile(profile, **settings)
  File "/usr/local/lib/python3.6/site-packages/py2neo/__init__.py", line 475, in __init__
    super(ServiceProfile, self).__init__(profile, **settings)
  File "/usr/local/lib/python3.6/site-packages/py2neo/__init__.py", line 190, in __init__
    self._apply_settings(**settings)
  File "/usr/local/lib/python3.6/site-packages/py2neo/__init__.py", line 512, in _apply_settings
    auth, user, password, **other)
  File "/usr/local/lib/python3.6/site-packages/py2neo/__init__.py", line 293, in _apply_settings
    raise ValueError("The following settings are not supported: %r" % other)
ValueError: The following settings are not supported: {'http_port': 7474}

pip3 install py2neo==
Collecting py2neo==
  Could not find a version that satisfies the requirement py2neo== (from versions: 4.0.0, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.2.0, 4.3.0, 2020.0.0, 2020.1.0, 2020.1.1, 2021.0.0, 2021.0.1, 2021.1.0, 2021.1.1, 2021.1.2, 2021.1.3, 2021.1.4, 2021.1.5, 2021.2.0, 2021.2.1, 2021.2.2, 2021.2.3)
No matching distribution found for py2neo==

python3 chat_graph.py
python3: can't open file 'chat_graph.py': [Errno 2] No such file or directory
[bj@fe1 QASystemOnMedicalKG]$ python3 chatbot_graph.py
Traceback (most recent call last):
  File "chatbot_graph.py", line 7, in <module>
    from question_classifier import *
  File "/home/bj/git/QASystemOnMedicalKG/question_classifier.py", line 8, in <module>
    import ahocorasick
ModuleNotFoundError: No module named 'ahocorasick'

sudo pip3 install pyahocorasick -i https://pypi.tuna.tsinghua.edu.cn/simple/
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting pyahocorasick
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/7f/c2/eae730037ae1cbbfaa229d27030d1d5e34a1e41114b21447d1202ae9c220/pyahocorasick-1.4.2.tar.gz (321kB)
    100% |████████████████████████████████| 327kB 1.2MB/s
Installing collected packages: pyahocorasick
  Running setup.py install for pyahocorasick ... error
    Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ic8kcxr4/pyahocorasick/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wfqjc412-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'ahocorasick' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DAHOCORASICK_UNICODE= -I/usr/include/python3.6m -c pyahocorasick.c -o build/temp.linux-x86_64-3.6/pyahocorasick.o
    In file included from pyahocorasick.c:13:
    common.h:15:10: 致命错误：Python.h：没有那个文件或目录
     #include <Python.h>
              ^~~~~~~~~~
    编译中断。
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ic8kcxr4/pyahocorasick/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wfqjc412-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ic8kcxr4/pyahocorasick/

docker EOFError: EOF when reading a line
